config/routes.rb
Devise4::Application.routes.draw do
  devise_for :users

  resources :posts do
    get 'create_and_get_like_count'
    get 'get_liked_users_for_post'
  end
match 'asd'=>"posts#edit"
match 'abc'=> "posts#update"

resources :chat_rooms
resources :users do
  resources :posts
end

get 'tags/:tag', to: 'posts#index', as: :tag
get '/comment'=>'posts#create_comment'
get '/get_liked_users_hover'=>'posts#get_liked_users_hover'
  root :to => "posts#index"

  resources :posts do
    collection do
      get 'new'      
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id, :user_id
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :post_id, :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  attr_accessible :body, :title, :user_id, :image,:video,:tag_list, :you_tube_video
  validates :title,  presence: true, length: { maximum: 20 }
  validates :body,  presence: true, length: { maximum: 5000 }
  validates :user_id,  presence: true
  belongs_to :user
  has_many :comments
  has_attached_file :image,styles:{large: "600x600",medium: "300x300>",thumb:"50x50#"},:path => ':attachment/:id/:style.:extension',
    :storage        => :s3,
    :s3_host_alias  => 'dev.1stmile.in',
    :s3_credentials => File.join(Rails.root, 'config', 'aws.yml')
  has_attached_file :video,:path => ':attachment/:id/:style.:extension',
    :storage        => :s3,
    :s3_host_alias  => 'dev.1stmile.in',
    :s3_credentials => File.join(Rails.root, 'config', 'aws.yml')
 #validates_attachement_content_type :image,content_type:/\Aimage\/.*\z/
 validates_attachment_content_type :image,:content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif','image/vob']
 validates_attachment_content_type :video,:content_type => ['video/mp4']
acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
         has_many :comments
  # attr_accessible :title, :body
  after_create :send_email
  def send_email
  	UserMailer.send_mail(self.email).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  Devise::Controllers::Helpers#stored_location_for


  def after_sign_in_path_for(resource_or_scope)
  	posts_path
	end

  def after_sign_out_path_for(resource_or_scope)
    #request.referrer
    new_post_path
  end

  def after_update_path_for(resource_or_scope)
    new_post_path
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate_user!


  def new
    @current_user = current_user
    @post = Post.new
    render layout: "layout3"
  end

  def index
    if params[:tag]
    @post = Post.tagged_with(params[:tag])
    else
    @post = Post.all
    end
    render layout: "layout4"
  end


  def edit
    @post = Post.find(params[:id])
    if(@post.user_id != current_user.id)
      return redirect_to posts_path flash[:notice] = "you are not permitted to edit this post::it belongs to other user "
    end
    render layout: "layout5"
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to posts_path :notice=>"your post has been updated"
    else
      render 'edit'
    end
  end


  def destroy
    @post = Post.find(params[:id])
    if(@post.user_id == current_user.id)
      @post.destroy
      redirect_to posts_path
    else
       redirect_to posts_path  flash[:notice] = "you are not permitted to delete this post::it belongs to other user "
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      p "123"
      p @post
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post=Post.find(params[:id])
  end

  def create_comment    
    @text_id=Time.now
    @post_id=params[:id]
    @content=params[:content]    
    comment=Comment.new(post_id: params[:id].to_i,content: params[:content],user_id: current_user.id)
    comment.save!
  end

  def create_and_get_like_count
    @flag=0
    like_or_not=Like.find_by_post_id_and_user_id(params[:post_id],current_user.id)
    if like_or_not.present?
      like_or_not.destroy
      @flag=1
    else
      like=Like.new(post_id: params[:post_id],user_id: current_user.id)    
      like.save!            
    end
    @post_id=params[:post_id]
    @like_count=Like.where(post_id: params[:post_id]).count    
  end

  def get_liked_users_for_post    
    @post_id=params[:post_id]
  end

  def get_liked_users_hover
    usrs=Like.where(post_id: params[:id].to_i).collect(&:user_id)
    arr=[]
    User.find_each do |usr|
      arr<<User.find(usr).email
    end    
    respond_to do |format|
      format.js {render :json=>arr}
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :body, :user_id,:image,:video,:tag_list,:you_tube_video)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/chat_rooms/index.html.erb
<%="welcome"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Devise4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/layout2.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
#navlist li
{
display: inline;
list-style-type: none;
padding-right: 30px;

float: right;
}
</style>
<head>
  <title>Devise4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navcontainer">
  <ul id="navlist">
  <li><%= button_to 'Chat Room', chat_rooms_path,:method => :get, :style=>"background:yellow"%></li>
  <li><%= button_to 'New post', new_post_path,:method => :get, :style=>"background:red"%></li>  
  <li><%= button_to 'Sign out', destroy_user_session_path,:method => :delete, :style=>"background:red"%></li>
</ul>
</div>

<%= yield %>

<br><br><br><br><br>
<%= button_to 'All posts', posts_path,:method => :get, :style=>"background:green"%>



</body>
</html>

app/views/layouts/layout3.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
#navlist li
{
display: inline;
list-style-type: none;
padding-right: 30px;

float: right;
}
</style>
<head>
  <title>Devise4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="navcontainer">
  <ul id="navlist">
<li><%= button_to 'Chat Room', chat_rooms_path,:method => :get, :style=>"background:yellow"%></li>
<li><%= button_to 'Sign out', destroy_user_session_path,:method => :delete, :style=>"background:yellow"%></li>
 <li><%= button_to 'All posts', posts_path,:method => :get, :style=>"background:yellow"%></li>

</ul>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/layout4.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
#navlist li
{
display: inline;
list-style-type: none;
padding-right: 30px;

float: right;
}

</style>

<head>
  <title>Devise4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div id="navcontainer">
  <ul id="navlist">
  <li><%= button_to 'Chat Room', chat_rooms_path,:method => :get, :style=>"background:yellow"%></li>
 <li><%= button_to 'Sign out', destroy_user_session_path,:method => :delete, :style=>"background:yellow"%></li>
  <li><%= button_to 'New post', new_post_path,:method => :get, :style=>"background:yellow"%></li>


</ul>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/layout5.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
#navlist li
{
display: inline;
list-style-type: none;
padding-right: 30px;

float: right;
}
</style>
<head>
  <title>Devise4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navcontainer">
  <ul id="navlist">
  <li><%= button_to 'Chat Room', chat_rooms_path,:method => :get, :style=>"background:yellow"%></li>
  <li><%= button_to 'New post', new_post_path,:method => :get, :style=>"background:yellow"%></li>
  <li><%= button_to 'Sign out', destroy_user_session_path,:method => :delete, :style=>"background:yellow"%></li>
</ul>
</div>

<%= yield %>

<br><br><br><br><br>
<%= button_to 'Back', posts_path,:method => :get, :style=>"background:green"%>



</body>
</html>

app/views/posts/_comment.html.erb
<div class="panel panel-primary">
 <div class="panel-heading" id="<%=id%>" style="min-height: 5; max-height: 5;">
 <%=@content%>
 </div>                      
</div>

app/views/posts/_like_count.html.erb
<span style="color: #337AB7;">
<%= link_to "("+count.to_s+")",post_get_liked_users_for_post_path(:post_id=>@post_id),:remote=>true,method: :get %>
</span>

app/views/posts/_list_liked_users.html.erb
<%user_id=Like.where(post_id: post_id).collect(&:user_id)%>
<%user_id.each do |usr|%>
  <%=User.find(usr.to_i).email%>
<%end%>

app/views/posts/_modal_dialog.html.erb
<div class="modal-dialog overlay" role="document" style="display: none;" width="100" height="100" id="modal-dialog_<%=post_id%>">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close close1" data-dismiss="modal" aria-label="Close" closeid="<%=post_id%>">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title">Modal title</h4>
    </div>
    <div class="modal-body">
      <p>One fine body&hellip;</p>
    </div>
    <div class="modal-footer">      
      <button type="button" class="btn btn-primary close1" closeid="<%=post_id%>">Close</button>
    </div>
  </div>
</div>

app/views/posts/create_and_get_like_count.js.erb
$('#like_'+'<%=@post_id%>').html("<%= escape_javascript render(:partial => 'posts/like_count',:locals => { :count => @like_count }) %>");
<%if @flag==1%>	
	$('#liked'+'<%=@post_id%>').css('color','#337AB7');
<%else%>
	$('#liked'+'<%=@post_id%>').css('color','blue');
<%end%>

app/views/posts/create_comment.js.erb
$('#commented_<%=@post_id%>').append("<%= escape_javascript render(:partial => 'posts/comment',:locals => { :id => @text_id }) %>");
$('#commented_<%=@post_id%>').show();	
$('.text_').val("");

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
label {color: yellow}
body {background-image: url("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTf-L2B8JFJU5dNp5B6k02I5cqW6rC7KZ0juQO8aH0D97CdM4uXrQ");
 }
 .container {
  margin:1%;

}
label {display: block;}

</style>
<body >

<div class="page-header">
<h1>Editing posts</h1>
</div>
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <div class="container">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  </p>


<p>
    <div class="container">
<%= f.label :tag_list, "Tags (separated by commas)" %><br />
<%= f.text_field :tag_list %>
</div>
  </p>


<p>
  <div class="container">
<%= f.label :image%><br>
<%= f.file_field :image%><br>
</div>
</p>

  <p>
    <div class="container">
    <%= f.label :body %><br>
    <%= f.text_area :body, :rows=>"6",:cols =>135 %>
  </div>
  </p>

<p>
  <div class="container">
<%= f.label "you tube video url"%>
<%= f.text_field :you_tube_video%>
</div>
</p>

<p>
  <div class="container">
<%= f.label :video%>
<%= f.file_field :video%>
</div>
</p>
<br>
  <p>
    <div class="container">
    <%=f.submit %>
  </div>
  </p>

<% end %>

</body>
</html>

app/views/posts/get_liked_users_for_post.js.erb
$('#modal-dialog_<%=@post_id%>').show({modal: true});
$('.modal-body').html("<%= escape_javascript render(:partial => 'posts/list_liked_users',:locals => { :post_id => @post_id }) %>");
$('#modal-dialog_<%=@post_id%>').draggable();

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
label {color: red}
th {color:yellow}
link_to {color: red;}
td {color:green}
iframe {color:black}
body {background-image: url("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTf-L2B8JFJU5dNp5B6k02I5cqW6rC7KZ0juQO8aH0D97CdM4uXrQ");
color: black;
 }
 h1 {color:white}
.temp{
  color: red
}
#tag_cloud {
  width: 400px;
  line-height: 1.6em;
  .s { font-size: 0.8em; color: red;}
  .m { font-size: 1.2em;color: red; }
  .l { font-size: 1.8em; color: red;}

}
.text_ {
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
}

.overlay{
  position: absolute;
  top: -35px;
  left: 65px;
  width: 40%;
  height: 34%;
  z-index: 10;
  background-color: #FFFFFF;
}       


sub {
  bottom: -0.99em;
  right: -em;
  right: -1em;
}

</style>

<script type="text/javascript">  
  $(function(){              
        
    $('.modal-dialog').css('width','250px');          

    $('.close1').on('click',function(event){      
      $('#modal-dialog_'+$(this).attr('closeid')).hide({modal: true});
    });

   


    $(".like_id").hover(function() {
      // $("#like_id").attr('title','giri');                   
      var postid=$(this).attr('post_id');
      $.get('/get_liked_users_hover', {id: $(this).attr('post_id')}, function(data) { 
        var usrs=JSON.parse(data);        
        $('#liked'+postid).attr('title',usrs.join("\n"));        
      });        

    });

    $('.text_comment').hide();  

    $('.link_to_comment').on('click',function(event){ 
      event.preventDefault();           
      var temp="#text_comment_"+ $(this).attr("id");      
      $(temp).show();
    });

    $(".text_").keyup(function (e) {            
      if (e.keyCode == 13) {                                 
        $.get('/comment', {content: $(this).val(),id: $(this).attr('val')}, function() {                    
        });        
      }
    });

  });

</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>  
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>

<body >

<div class="page-header">
<h1>All posts</h1>
</div>
<% if flash[:notice] %>
<%= flash[:notice] %>
  <% end %>

<div id="tag_cloud">
  <div class="panel panel-default">
    <div class="panel-heading custom_class" >
      <div class="panel-body">
        <h4>Tags:</h4>
          <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
      </div>
    </div>
  </div>
</div>
  <div class="row ">
    <div class="col-md-2 col-md-offset-1">
      <% @post.each do |msg| %>
        <div id="tag_cloud">
          <div class="panel panel-default">
            <div class="panel-heading custom_class" >
              <div class="panel-body">                                
                <%= link_to msg.title, post_path(msg) %>
                <%if msg.image.url!="/images/original/missing.png"%>
                  <%= link_to image_tag(msg.image.url(:thumb),:width => 70, :height => 70),post_path(msg)%>
                <%else%>
                  <%= link_to image_tag("http://www.bandit.fm/web/img/no-image.png",:size=>"70x70"),post_path(msg)%>                  
                <%end%>   
                <br><br><br>
                <%if msg.video.url!="/videos/original/missing.png" && msg.you_tube_video.present? %>
                  <% url="//www.youtube.com/embed/"+msg.you_tube_video.split("=").last%>
                    <video width="300" height="240" controls>
                      <source src="<%=msg.video.url%>" type="video/mp4">
                    </video>         
                    <br>                                               
                    <br>
                    <iframe width="300" height="240" src="<%=url%>" frameborder="0" allowfullscreen="allowfullscreen" id="iframe">
                    </iframe>                                                              
                <%elsif msg.video.url!="/videos/original/missing.png"%>
                  <video width="300" height="240" controls>
                    <source src="<%=msg.video.url%>" type="video/mp4">
                  </video>
                <%else msg.you_tube_video.present?%>
                  <% url="//www.youtube.com/embed/"+msg.you_tube_video.split("=").last%>
                  <iframe width="300" height="240" src="<%=url%>" frameborder="0" allowfullscreen="allowfullscreen" id="iframe"></iframe>
                <%end%>
                <br>                
                <%= msg.body.first(120)%> <%=link_to "more.......",post_path(msg)%>
                <br><br>                
                <div class="row ">                  
                  <div class="col-md-4">
                    <%= link_to 'comment', '#' ,:id=>"#{msg.id}",:class=>"link_to_comment",:style=>"font-style: italic;"%>
                  </div>

                  <div class="col-md-4">                    
                    <div class="row ">
                      <div class="col-md-3">                    
                        <%likeornot=nil%>
                        <%likeornot=Like.find_by_post_id_and_user_id(msg.id,current_user.id)%>
                        <%if likeornot.present?%>
                          <%= link_to 'like',post_create_and_get_like_count_path(:post_id=>msg.id), method: :get,:remote => true, :class=>"like_id" ,:id=>"liked"+msg.id.to_s,:post_id=>msg.id,:style=>"color: blue; font-style: italic;"%>
                        <%else%>
                          <%= link_to 'like',post_create_and_get_like_count_path(:post_id=>msg.id), method: :get,:remote => true, :class=>"like_id" ,:id=>"liked"+msg.id.to_s,:post_id=>msg.id,:style=>"font-style: italic;"%>
                        <%end%>                      
                        <%=render :partial=>"posts/modal_dialog", :locals => { :post_id => msg.id }%>
                      </div>
                      <div class="col-md-3">                    
                        <div id="like_<%=msg.id%>">                        
                        </div>                        
                      </div>                      
                    </div>
                  </div>

                  <div class="col-md-4">
                    <%= link_to 'tag', post_path(msg),:style=>"font-style: italic;" %>
                  </div>
                  <div id="commented_<%=msg.id%>" class="commented">
                    <br><br>                                        
                    <%Comment.where(post_id: msg.id).each do |comm|%>
                      <div class="panel panel-primary">
                        <div class="panel-heading" id="<%=Time.now%>" style="min-height: 5; max-height: 5;">
                          <%=comm.content%><sub><%=User.find(comm.user_id).email%></sub>
                        </div>                      
                      </div>
                    <%end%>
                  </div>
                  <div id="text_comment_<%=msg.id%>" style="display:none;" class="text_comment">
                    <br><br>
                    <%= text_field_tag :comment,nil,:size => "40",:val=>msg.id,:class=>"text_" %> 
                    <br>                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<style type="text/css">
label {color: yellow}
body {background-image: url("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTf-L2B8JFJU5dNp5B6k02I5cqW6rC7KZ0juQO8aH0D97CdM4uXrQ");
color:black;
 }

 h1 {color:white}

.container {
  margin:1%;

}
label {display: block;color: lightblue;}

</style>
<body >



<div class="page-header">
<h1 >Add post</h1>
</div>

<% if @post.errors.any? %>

    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<%= form_for :post,url:posts_path do |f| %>



<p>
  <div class="container">
  <%= f.label :title %>
  <%= f.text_field :title%><br>
</div>
</p>


<p>
<div class="container">
<%= f.label :tag_list, "Tags (separated by commas)" %><br />
<%= f.text_field :tag_list %>
</div>
</p>



  <p>
 <div class="container">
  <%=f.label :content %>
  <%= f.text_area :body, :rows=>"6",:cols =>85 %>
  </div>
   <%= f.hidden_field :user_id, :value => current_user.id %>
  </p>




<p>
<div class="container">
<%= f.label :image%>
<%= f.file_field :image%>
</div>
</p>
<br>
<p>
  <div class="container">
<%= f.label "Youtube Video URL" %>
<%= f.text_field :you_tube_video%>
</div>
</p>

<br>
<p>
<div class="container">
<%= f.label :video%>
<%= f.file_field :video%>
</div>
</p>
</br>

<br>
<p>
  <div class="container">
  <%= f.submit%>
</div>
  </p>
  <%end%>


</body>
</html>

app/views/posts/show.html.erb
<style type="text/css">
#navlist li
{
display: inline;
list-style-type: none;
padding-right: 30px;

float: right;
}
</style>
<div class="panel panel-default">
  <div class="panel-heading custom_class" >
  <div class="panel-body">
    <div id="navcontainer">
  <ul id="navlist">
    <li><%= button_to 'Edit', edit_post_path(@post),:method => :get, :style=>"background:lightblue"%></li>
    <li><%= button_to 'New post', new_post_path,:method => :get, :style=>"background:lightblue"%></li>
    <li><%= button_to 'Sign out', destroy_user_session_path,:method => :delete, :style=>"background:lightblue"%></li>
    <li><%= button_to 'All posts', posts_path,:method => :get, :style=>"background:lightblue"%></li>
  </ul>
</div>
<h2> <%= @post.title%></h2>

 <br><br><br>

 <br><br><br>
 <%if @post.image.url!="/images/original/missing.png"%>
  <%= image_tag(@post.image.url,:size=>"300x300") %>
 <%else%>
  <%= image_tag("http://www.bandit.fm/web/img/no-image.png",:size=>"300x300") %>
 <%end%> 

 

<br><br><br>
description:
<%=@post.body%><br>
<br><br><br>
<h4>Tags:</h4><%=@post.tag_list%>
<br><br><br>


<div class ="row">
<%if @post.video.url!="/videos/original/missing.png"%>
  <div class="col-md-6">
    <video width="300" height="300" controls>
      <source src="<%=@post.video.url%>" type="video/mp4">
    </video>
  </div>
<%end%>
<%if @post.you_tube_video.present? %>
  <div class="col-md-6">
    <% url="//www.youtube.com/embed/"+@post.you_tube_video.split("=").last%>
    <iframe width="300" height="300" src="<%=url%>" frameborder="0" allowfullscreen="allowfullscreen">    
    </iframe>  
  </div>
<%end%>
</div>




</div>
</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>